informacao = input('escreva algo: ')
print('o tipo primitivo desse valor é ', type(informacao))
print('É composto só por espaços? ', informacao.isspace())
print('É um número? ', informacao.isnumeric())
print('É uma letra? ', informacao.isalpha())
print('É um número? ', informacao.isalnum())
print('Está em maiúsculas? ', informacao.isupper())
print('Esta é minúsculas? ', informacao.islower())
print('inicia com letra maiúscula? ', informacao.istitle())